version: '2'

services:
  db:
    image: postgres:12.18-alpine3.19
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: no
    ports:
      - 8081:8080
    environment:
      ADMINER_DEFAULT_SERVER: db
      ADMINER_DESIGN: ng9
  frontend:
    build: frontend
    restart: always
    image: hongo.io/hongo/vibration-frontend:latest
    ports: 
      - 5004:5173
    environment:
      - VITE_API_URL
  backend:
    build: backend
    environment:
    - SECRET_KEY
    - DB_USER
    - DB_PASSWORD
    - DB_HOST=db
    - DB_TYPE
    - STORAGE_PATH
    - DB_DATABASE
    - DB_PORT
    - MAIL_SERVER
    - MAIL_PORT
    - MAIL_USERNAME
    - MAIL_USE_TLS
    - MAIL_PASSWORD
    - MAIL_DOMAIN
    restart: always
    image: hongo.io/hongo/iot-backend:latest
    ports: 
      - 5003:5000
